apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  clusterIP: None # Required: This makes it "Headless" for stable DNS
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
spec:
  serviceName: "postgres-db" # Connects to the Headless Service
  replicas: 3               # We are running a 3-node "Pet" cluster
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        resources:          # SRE Best Practice: Prevent OOM (Out of Memory)
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword" 
        volumeMounts:
        - name: pg-data      # This name must match the template below
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:      # The "Magic" that gives each Pod a unique disk
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard" # In EKS, use "gp3"; in Minikube, use "standard"
      resources:
        requests:
          storage: 1Gi